-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.10.1-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for example
CREATE DATABASE IF NOT EXISTS `laravel` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_persian_ci */;
USE `laravel`;

-- Dumping structure for table example.countries
CREATE TABLE IF NOT EXISTS `countries` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `gallery_id` bigint(20) unsigned DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `countries_gallery_id_foreign` (`gallery_id`),
    CONSTRAINT `countries_gallery_id_foreign` FOREIGN KEY (`gallery_id`) REFERENCES `galleries` (`id`) ON DELETE SET NULL
    ) ENGINE=InnoDB AUTO_INCREMENT=234 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table example.countries: ~232 rows (approximately)
INSERT INTO `countries` (`id`, `name`, `title`, `gallery_id`) VALUES
                                                                     (1, 'Afghanistan', 'افغانستان', 1),
                                                                     (2, 'Aland Islands', 'جزایر الند', NULL),
                                                                     (3, 'Albania', 'آلبانی', 2),
                                                                     (4, 'Algeria', 'الجزایر', 3),
                                                                     (5, 'American Samoa', 'ساموآی آمریکا', NULL),
                                                                     (6, 'Andorra', 'آندورا', 4),
                                                                     (7, 'Angola', 'آنگولا', 5),
                                                                     (8, 'Anguilla', 'آنگویلا', NULL),
                                                                     (9, 'Antarctica', 'جنوبگان', NULL),
                                                                     (10, 'Antigua and Barbuda', 'آنتیگوآ و باربودا', 6),
                                                                     (11, 'Argentina', 'آرژانتین', 7),
                                                                     (12, 'Armenia', 'ارمنستان', 8),
                                                                     (13, 'Aruba', 'آروبا', NULL),
                                                                     (14, 'Australia', 'استرالیا', 9),
                                                                     (15, 'Austria', 'اتریش', 10),
                                                                     (16, 'Azerbaijan', 'آذربایجان', 11),
                                                                     (17, 'Bahamas', 'باماها', 12),
                                                                     (18, 'Bahrain', 'بحرین', 14),
                                                                     (19, 'Bangladesh', 'بنگلادش', 13),
                                                                     (20, 'Barbados', 'باربادوس', 15),
                                                                     (21, 'Belarus', 'بلاروس', 16),
                                                                     (22, 'Belgium', 'بلژیک', 17),
                                                                     (23, 'Belize', 'بلیز', 18),
                                                                     (24, 'Benin', 'بنین', 19),
                                                                     (25, 'Bermuda', 'برمودا', NULL),
                                                                     (26, 'Bhutan', 'بوتان', 20),
                                                                     (27, 'Bolivia', 'بولیوی', 21),
                                                                     (28, 'Bonaire, Sint Eustatius and Saba', 'بونیت سینت', NULL),
                                                                     (29, 'Bosnia and Herzegovina', 'بوسنی هرزگوین', 22),
                                                                     (30, 'Botswana', 'بوتسوانا', 23),
                                                                     (31, 'Bouvet Island', 'جزیزه بووه', NULL),
                                                                     (32, 'Brazil', 'برزیل', 24),
                                                                     (34, 'Brunei Darussalam', 'برونئی', 25),
                                                                     (35, 'Bulgaria', 'بلغارستان', 26),
                                                                     (36, 'Burkina Faso', 'بورکینافاسو', 27),
                                                                     (37, 'Burundi', 'بوروندی', 28),
                                                                     (38, 'Cambodia', 'کامبوج', 31),
                                                                     (39, 'Cameroon', 'کامرون', 32),
                                                                     (40, 'Canada', 'کانادا', 33),
                                                                     (41, 'Cape Verde', 'کیپ ورد', NULL),
                                                                     (42, 'Cayman Islands', 'جزایر کیمن', NULL),
                                                                     (43, 'Central African Republic', 'جمهوری آفریقا مرکزی', 34),
                                                                     (44, 'Chad', 'چاد', 35),
                                                                     (45, 'Chile', 'شیلی', 36),
                                                                     (46, 'China', 'چین', 37),
                                                                     (47, 'Christmas Island', 'جزیره کریسمس', NULL),
                                                                     (48, 'Cocos (Keeling) Islands', 'جزایر کوکوس', NULL),
                                                                     (49, 'Colombia', 'کلمبیا', 38),
                                                                     (50, 'Comoros', 'کومور', 39),
                                                                     (51, 'Congo', 'کونگو', 40),
                                                                     (52, 'Cook Islands', 'جزایر کوک', NULL),
                                                                     (53, 'Costa Rica', 'کاستاریکا', 41),
                                                                     (54, 'Cote D\'Ivoire', 'ساحل عاج', 29),
(55, 'Croatia', 'کرواسی', 42),
(56, 'Cuba', 'کوبا', 43),
(57, 'Curacao', 'کوراسائو', NULL),
(58, 'Cyprus', 'قبرس', 44),
(59, 'Czech Republic', 'چک', 45),
(60, 'Denmark', 'دانمارک', 46),
(61, 'Djibouti', 'جیبوتی', 47),
(62, 'Dominica', 'دومینیکا', 48),
(63, 'Dominican Republic', 'جمهوری دومینیکا', 49),
(64, 'Ecuador', 'اکوادور', 52),
(65, 'Egypt', 'مصر', 53),
(66, 'El Salvador', 'السالوادور', 54),
(67, 'Equatorial Guinea', 'گینه استوایی', 55),
(68, 'Eritrea', 'اریتره', 56),
(69, 'Estonia', 'استونی', 57),
(70, 'Ethiopia', 'اتیوپی', 59),
(71, 'Falkland Islands (Malvinas)', 'جزایر فالکلند', NULL),
(72, 'Faroe Islands', 'جزایر فارو', NULL),
(73, 'Fiji', 'فیجی', 60),
(74, 'Finland', 'فنلاند', 61),
(75, 'France', 'فرانسه', 62),
(76, 'French Guiana', 'گویان فرانسه', NULL),
(77, 'French Polynesia', 'پلی نزی فرانسه', NULL),
(78, 'French Southern Territories', 'جنوبی و جنوبگان فرانسه', NULL),
(79, 'Gabon', 'گابن', 63),
(80, 'Gambia', 'گامبیا', 64),
(81, 'Georgia', 'گرجستان', 65),
(82, 'Germany', 'آلمان', 66),
(83, 'Ghana', 'غنا', 67),
(84, 'Gibraltar', 'جبل الطارق', NULL),
(85, 'Greece', 'یونان', 68),
(86, 'Greenland', 'گرینلند', NULL),
(87, 'Grenada', 'گرنادا', 69),
(88, 'Guadeloupe', 'گوادلوپ', NULL),
(89, 'Guam', 'گوآم', NULL),
(90, 'Guatemala', 'گواتمالا', 70),
(91, 'Guernsey', 'گرنزی', NULL),
(92, 'Guinea', 'گینه', 71),
(93, 'Guinea-Bissau', 'گینه بیسائو', 72),
(94, 'Guyana', 'گویان', 73),
(95, 'Haiti', 'هائیتی', 74),
(96, 'Heard Island and Mcdonald Islands', 'هرد و مک دونالد', NULL),
(97, 'Holy See (Vatican City State)', 'واتیکان', 75),
(98, 'Honduras', 'هندوراس', 76),
(99, 'Hong Kong', 'هنگ کنگ', NULL),
(100, 'Hungary', 'مجارستان', 77),
(101, 'Iceland', 'ایسلند', 78),
(102, 'India', 'هند', 79),
(103, 'Indonesia', 'اندونزی', 80),
(104, 'Iran', 'ایران', 81),
(105, 'Iraq', 'عراق', 82),
(106, 'Ireland', 'ایرلند', 83),
(107, 'Isle of Man', 'جزیره من', NULL),
(108, 'Israel', 'اسرائیل', 84),
(109, 'Italy', 'ایتالیا', 85),
(110, 'Jamaica', 'جامائیکا', 86),
(111, 'Japan', 'ژاپن', 87),
(112, 'Jersey', 'جرزی', NULL),
(113, 'Jordan', 'اردن', 88),
(114, 'Kazakhstan', 'قزاقستان', 89),
(115, 'Kenya', 'کنیا', 90),
(116, 'Kiribati', 'کیریباتی', 91),
(117, 'Korea, Republic of', 'کره جنوبی', 161),
(118, 'Kosovo', 'کوزوو', NULL),
(119, 'Kuwait', 'کویت', 92),
(120, 'Kyrgyzstan', 'قرقیزستان', 93),
(121, 'Lao People\'s Democratic Republic', 'لائوس', 94),
                                                                     (122, 'Latvia', 'لتونی', 95),
                                                                     (123, 'Lebanon', 'لبنان', 96),
                                                                     (124, 'Lesotho', 'لسوتو', 97),
                                                                     (125, 'Liberia', 'لیبریا', 98),
                                                                     (126, 'Libyan Arab Jamahiriya', 'لیبی', 99),
                                                                     (127, 'Liechtenstein', 'لیختن اشتاین', 100),
                                                                     (128, 'Lithuania', 'لیتوانی', 101),
                                                                     (129, 'Luxembourg', 'لوکزامبورگ', 102),
                                                                     (130, 'Macao', 'ماکائو', NULL),
                                                                     (131, 'Macedonia, the Former Yugoslav Republic of', 'مقدونیه', NULL),
                                                                     (132, 'Madagascar', 'ماداگاسکار', 103),
                                                                     (133, 'Malawi', 'مالاوی', 104),
                                                                     (134, 'Malaysia', 'مالزی', 105),
                                                                     (135, 'Maldives', 'مالدیو', 106),
                                                                     (136, 'Mali', 'مالی', 107),
                                                                     (137, 'Malta', 'مالت', 108),
                                                                     (138, 'Marshall Islands', 'جزایر مارشال', 109),
                                                                     (139, 'Martinique', 'مارتینیک', NULL),
                                                                     (140, 'Mauritania', 'موریتانی', 110),
                                                                     (141, 'Mauritius', 'موریس', 111),
                                                                     (142, 'Mayotte', 'مایوت', NULL),
                                                                     (143, 'Mexico', 'مکزیک', 112),
                                                                     (144, 'Micronesia, Federated States of', 'میکرونزی', 113),
                                                                     (145, 'Moldova, Republic of', 'مولداوی', 114),
                                                                     (146, 'Monaco', 'موناکو', 115),
                                                                     (147, 'Mongolia', 'مغولستان', 116),
                                                                     (148, 'Montenegro', 'مونته نگرو', 117),
                                                                     (149, 'Montserrat', 'مونتراست', NULL),
                                                                     (150, 'Morocco', 'مراکش', 118),
                                                                     (151, 'Mozambique', 'موزامبیک', 119),
                                                                     (152, 'Myanmar', 'میانمار', 120),
                                                                     (153, 'Namibia', 'نامیبیا', 121),
                                                                     (154, 'Nauru', 'نائورو', 122),
                                                                     (155, 'Nepal', 'نپال', 123),
                                                                     (156, 'Netherlands', 'هلند', 124),
                                                                     (157, 'New Caledonia', 'کالدونیای جدید', NULL),
                                                                     (158, 'New Zealand', 'نیوزلند', 125),
                                                                     (159, 'Nicaragua', 'نیکاراگوئه', 126),
                                                                     (160, 'Niger', 'نیجر', 127),
                                                                     (161, 'Nigeria', 'نیجریه', 128),
                                                                     (162, 'Niue', 'نیووی', NULL),
                                                                     (163, 'Norfolk Island', 'نورفک', NULL),
                                                                     (164, 'Northern Mariana Islands', 'ماریانای شمالی', NULL),
                                                                     (165, 'Norway', 'نروژ', 130),
                                                                     (166, 'Oman', 'عمان', 131),
                                                                     (167, 'Pakistan', 'پاکستان', 132),
                                                                     (168, 'Palau', 'پالائو', 133),
                                                                     (169, 'Panama', 'پاناما', 134),
                                                                     (170, 'Papua New Guinea', 'پاپوآ گینه نو', 135),
                                                                     (171, 'Paraguay', 'پاراگوئه', 136),
                                                                     (172, 'Peru', 'پرو', 137),
                                                                     (173, 'Philippines', 'فیلیپین', 138),
                                                                     (174, 'Pitcairn', 'پیت کرن', NULL),
                                                                     (175, 'Poland', 'لهستان', 139),
                                                                     (176, 'Portugal', 'پرتفال', 140),
                                                                     (177, 'Puerto Rico', 'پورتوریکو', NULL),
                                                                     (178, 'Qatar', 'قطر', 141),
                                                                     (179, 'Reunion', 'رئونیون', NULL),
                                                                     (180, 'Romania', 'رومانی', 142),
                                                                     (181, 'Rwanda', 'رواندا', 144),
                                                                     (182, 'Saint Barthelemy', 'سن بارتلمی', NULL),
                                                                     (183, 'Saint Lucia', 'سنت لوسیا', 146),
                                                                     (184, 'Samoa', 'ساموآ', 147),
                                                                     (185, 'San Marino', 'سن مارینو', 148),
                                                                     (186, 'Sao Tome and Principe', 'سائوتومه و پرنسیپ', 149),
                                                                     (187, 'Saudi Arabia', 'عربستان صعودی', 150),
                                                                     (188, 'Senegal', 'سنگال', 151),
                                                                     (189, 'Serbia', 'صربستان', 152),
                                                                     (190, 'Seychelles', 'سیشل', 153),
                                                                     (191, 'Sierra Leone', 'سیرالئون', 154),
                                                                     (192, 'Singapore', 'سنگاپور', 155),
                                                                     (193, 'Sint Maarten', 'سن مارنن', NULL),
                                                                     (194, 'Slovakia', 'اسلواکی', 156),
                                                                     (195, 'Slovenia', 'اسلوونی', 157),
                                                                     (196, 'Solomon Islands', 'جزایر سلیمان', 158),
                                                                     (197, 'Somalia', 'سومالی', 159),
                                                                     (198, 'South Africa', 'آقریقای جنوبی', 160),
                                                                     (199, 'South Sudan', 'سودان جنوبی', 162),
                                                                     (200, 'Spain', 'اسپانیا', 163),
                                                                     (201, 'Sri Lanka', 'سری لانکا', 164),
                                                                     (202, 'Sudan', 'سودان', 167),
                                                                     (203, 'Suriname', 'سورینام', 168),
                                                                     (204, 'Swaziland', 'اسواتینی', NULL),
                                                                     (205, 'Sweden', 'سوئد', 169),
                                                                     (206, 'Switzerland', 'سوئیس', 170),
                                                                     (207, 'Syrian Arab Republic', 'سوریه', 171),
                                                                     (208, 'Taiwan', 'تایوان', NULL),
                                                                     (209, 'Tajikistan', 'تاجیکستان', 172),
                                                                     (210, 'Tanzania, United Republic of', 'تانزانیا', 173),
                                                                     (211, 'Thailand', 'تایلند', 174),
                                                                     (212, 'Timor-Leste', 'تیمور شرقی', 175),
                                                                     (213, 'Togo', 'توگو', 176),
                                                                     (214, 'Tokelau', 'توکلائو', NULL),
                                                                     (215, 'Tonga', 'تونگا', 177),
                                                                     (216, 'Trinidad and Tobago', 'ترینداد و توباگو', 178),
                                                                     (217, 'Tunisia', 'تونس', 179),
                                                                     (218, 'Turkey', 'ترکیه', 180),
                                                                     (219, 'Turkmenistan', 'ترکمنستان', 181),
                                                                     (220, 'Tuvalu', 'تووالو', 182),
                                                                     (221, 'Uganda', 'اوگاندا', 186),
                                                                     (222, 'Ukraine', 'اوکراین', 187),
                                                                     (223, 'United Arab Emirates', 'امارات متحده عربی', 183),
                                                                     (224, 'United Kingdom', 'بریتانیا', 184),
                                                                     (225, 'United States', 'ایالات متحده آمریکا', 185),
                                                                     (226, 'Uruguay', 'اروگوئه', 188),
                                                                     (227, 'Uzbekistan', 'ازبکستان', 189),
                                                                     (228, 'Vanuatu', 'وانواتو', 190),
                                                                     (229, 'Venezuela', 'ونزوئلا', 191),
                                                                     (230, 'Vietnam', 'ویتنام', 192),
                                                                     (231, 'Yemen', 'یمن', 193),
                                                                     (232, 'Zambia', 'زامبیا', 194),
                                                                     (233, 'Zimbabwe', 'زیمبابوه', 195),
                                                                     (244,'Russian','روسیه',143);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
